server:
  port: 1111
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: WelcomeStar
#below code is for registering the actuator client with the acutator server    
  boot:
    admin:
      client:
        url: http://localhost:9090/
         